/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 会话列表
         * @description 当前用户的全部会话，按最后活跃时间倒序，不分页、不含消息正文
         */
        get: operations["list"];
        put?: never;
        /**
         * 新建会话
         * @description 创建空白会话，标题为默认值
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除会话
         * @description 连同其全部消息一并删除。幂等，重复删除不报错
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 会话消息列表
         * @description 按发送顺序返回该会话的全部消息
         */
        get: operations["messages"];
        put?: never;
        /**
         * 发送消息（SSE 流式）
         * @description 返回 text/event-stream，不套 Result 信封。
         *     事件协议：若干 delta → done →（仅新会话）title；生成失败则以 error 结束且本次回复不落库。
         *     每条事件都必须带 event 名，事件体均为 JSON。
         */
        post: operations["send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新生成（SSE 流式）
         * @description 删除该会话最后一条助手回复，用其前面那条用户消息重新生成——用户消息不会重复插入。
         *     事件协议与「发送消息」完全一致。
         */
        post: operations["regenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConversationVO: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** Format: date-time */
            updateTime?: string;
        };
        MessageVO: {
            content?: string;
            /** Format: date-time */
            createTime?: string;
            /** Format: int64 */
            id?: number;
            role?: string;
        };
        ResultConversationVO: {
            /** Format: int32 */
            code?: number;
            data?: components["schemas"]["ConversationVO"];
            message?: string;
        };
        ResultListConversationVO: {
            /** Format: int32 */
            code?: number;
            data?: components["schemas"]["ConversationVO"][];
            message?: string;
        };
        ResultListMessageVO: {
            /** Format: int32 */
            code?: number;
            data?: components["schemas"]["MessageVO"][];
            message?: string;
        };
        ResultVoid: {
            /** Format: int32 */
            code?: number;
            data?: unknown;
            message?: string;
        };
        SendMessageRequest: {
            content?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListConversationVO"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultConversationVO"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultVoid"];
                };
            };
        };
    };
    messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListMessageVO"];
                };
            };
        };
    };
    send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    regenerate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
}
